### PR TITLE
IDE-2768 minor updates

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@AndyWu2015 the only other thing that we need to make work is the "Restore Defaults" it doesn't work.  Can you add that?  thanks!

**Comment by AndyWu2015** [comment]
but it works well on my machine. could you double check it ?

**Comment by gamerson** [comment]
@AndyWu2015 it works fine, but the "Restore Defaults" button on the preference page doesn't work.  Can you add support for "restore defaults"?  There are multiple ways you can do that either by overriding "performDefaults()" method, or you can register a Preference initializer and you can set "default" values of those preferences.

**Comment by AndyWu2015** [comment]
yeah , Greg. But I've add a the defaults in preferences.ini in project.core project , and the restore default button on linux , windows, and even mac on my side worked well .  I don't konw why it didn't work on your machine , and I've sent a pr https://github.com/gamerson/liferay-ide/pull/1634, you can test it , and let me konw if any bug.

**Pull request closed without merging**
