### PR TITLE
IDE-3399 add tests

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @AndyWu2015 can you look at my changes to IDE-3399 and test them locally?

**Comment by gamerson** [comment]
If everything works you can send it back to me.

**Comment by AndyWu2015** [comment]
ok , got it

**Comment by AndyWu2015** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AndyWu2015** [comment]
close

**Pull request closed without merging**
